namespace PideServicio.Application.Features.Tickets.DTOs;

public sealed record TicketDetalleDto(
    Guid Id,
    string Codigo,
    string Titulo,
    string Descripcion,
    string Estado,
    string PrioridadSolicitante,
    string? PrioridadAdmin,
    string PrioridadEfectiva,
    Guid EmpresaId,
    Guid SucursalId,
    Guid AreaId,
    Guid TipoServicioId,
    Guid CategoriaId,
    Guid SolicitanteId,
    Guid? TecnicoId,
    string? Ubicacion,
    int? TiempoEstimadoMin,
    Guid? SlaId,
    DateTimeOffset? FechaLimitePrimeraAtencion,
    DateTimeOffset? FechaLimiteResolucion,
    byte? Valoracion,
    Guid? MotivoCancelacionId,
    DateTimeOffset FechaCreacion,
    DateTimeOffset? FechaAsignacion,
    DateTimeOffset? FechaInicioProceso,
    DateTimeOffset? FechaFinalizacionTecnico,
    DateTimeOffset? FechaValidacion,
    DateTimeOffset? FechaCierre,
    DateTimeOffset? FechaCancelacion,
    int Version,
    DateTimeOffset? UpdatedAt,
    string? TipoServicioNombre = null,
    string? SucursalNombre = null,
    string? AreaNombre = null,
    string? TecnicoNombre = null);
